import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#2196F3',
  income: '#4CAF50',
  expense: '#F44336',
  white: '#FFFFFF',
  black: '#000000',
  gray: '#9E9E9E',
  lightGray: '#F5F5F5',
  darkGray: '#757575',
  border: '#E0E0E0',
  background: '#FAFAFA',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingVertical: 10,
  },
  balanceCard: {
    backgroundColor: '#39c54e',
    marginHorizontal: 16,
    marginTop: 26,
    marginBottom: 8,
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 25,
  },
  amoutView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  amoutTxt: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '400',
  },
  amout: {
    fontSize: 20,
    color: '#fff',
    fontWeight: '700',
    marginTop: 3,
  },
  dateTxt: {
    fontSize: 16,
    color: '#fff',
    marginVertical: 10,
  },
  CardsContainer: {
    flexDirection: 'row',
    gap: 16,
    justifyContent: 'center',
    marginHorizontal: 16,
    marginBottom: 16,
  },
  card: {
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    elevation: 1,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    width: '46%',
  },
  iconIncome: {
    backgroundColor: '#bbecc2',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    height: 40,
    width: 40,
    marginBottom: 8,
  },
  iconExpense: {
    backgroundColor: '#faafaf',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    height: 40,
    width: 40,
    marginBottom: 8,
  },
  icomeTxt: {
    marginVertical: 3,
    color: '#7e7373',
    fontSize: 14,
  },
  icome: {
    marginVertical: 3,
    color: '#39c54e',
    fontWeight: '700',
    fontSize: 17,
  },
  monthTxt: {
    marginBottom: 8,
    color: '#7e7373',
    fontSize: 12,
  },
  expenseTxt: {
    marginVertical: 3,
    color: '#7e7373',
    fontSize: 14,
  },
  expense: {
    marginVertical: 3,
    color: '#ce3c14',
    fontWeight: '700',
    fontSize: 17,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    padding: 8,
    marginBottom: 8,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 8,
    marginHorizontal: 4,
  },
  activeTab: {
    backgroundColor: colors.primary,
  },
  tabText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.darkGray,
  },
  activeTabText: {
    color: colors.white,
  },
  transectionView: {
    flex: 1, // Changed from fixed height to flex:1
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  seeAllView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 10,
    // borderBottomWidth: 1,
    // borderBottomColor: colors.border,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.black,
  },
  viewAllText: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '500',
  },
  listContainer: {
    flexGrow: 1,
    paddingBottom: 10,
    marginHorizontal: -15,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyText: {
    fontSize: 16,
    color: colors.gray,
    textAlign: 'center',
    marginTop: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
